@baseUrl = https://cst8919-lab-2-appservices-egduc3esgwhzakg5.canadacentral-01.azurewebsites.net

### Successful Login
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=Password123

### Failed Login 1
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=badpass1

### Failed Login 2
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=badpass2

### Failed Login 3
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=badpass3

### Failed Login 4
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=badpass4

### Failed Login 5
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=badpass5